version: "3.7"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: on-failure

  bot:
    build:
      context: .
      args:
        - TARGETARCH=amd64
    restart: always
    depends_on:
      - db